version: "3.8"

networks:
  laravel:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: ./.docker/nginx/Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html:delegated
      - ./logs:/var/log/nginx
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: php
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel

  mysql:
    image: mariadb:10.3
    container_name: mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_USER: "laravel"
      MYSQL_PASSWORD: "laravel"
      MYSQL_ROOT_PASSWORD: "laravel"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 2000000000000
    depends_on:
      - mysql
    ports:
      - "81:80"
    networks:
      - laravel


