name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.6.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no -p 2223 peerawet@serveo.net << 'EOF'
            cd /deploy/docker-deploy-laravel
            git pull origin main
            docker-compose -f /deploy/docker-deploy-laravel/docker-compose.yml down
            docker-compose -f /deploy/docker-deploy-laravel/docker-compose.yml up -d --build
          EOF
